### ISSUE TITLE
TypeError: can't pickle weakref objects

### ISSUE THREAD

**Issue by Anderas2** [migvel/color_trace#11]
Hello;
the module threw "TypeError: can't pickle weakref objects" today at line 801 p.start()

As I have  only very simple graphics (black + white + transparent), is it possible without greater rework, to remove the multiprocessing?
I took a look at your code today and it seems to be a big part of your code.

Here's a dump of the error trace

my code:
    ctm.color_trace_multi(inputs=picpath,
                      outputs=outpath,
                      colors = 1,
                      processcount = 1)

error:
Traceback (most recent call last):

  File "<ipython-input-19-f26ed8e0dcf1>", line 4, in <module>
    processcount = 1)

  File "C:\Users\Andreas\25 Heroquest\Questimator\Code\Multicolor_Symbols\color_trace_multi.py", line 801, in color_trace_multi
    p.start()

  File "C:\Users\Andreas\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)

  File "C:\Users\Andreas\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "C:\Users\Andreas\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "C:\Users\Andreas\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\Andreas\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

**Comment by Fayzan-Bhatti** [comment]
I found similar error here [https://stackoverflow.com/questions/69769787/cant-pickle-weakref-objects-keras-mdoel](url)

**Comment by lennartkerkvliet** [comment]
Happens to me on Python 3.8 and above. Python 3.7 works fine.
